# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: minimal
  theme_night: minimal
  font: minimal
  font_size: L

# SEO

site_type: Person
local_business_type: ''
org_name: ''
description: ''
twitter: 'https://twitter.com/ivanderkelen'

# Contact (edit or remove options as required)

email: inne.vanderkelen [at] vub.be
#phone: +476 75 90 41
directions: Department of Hydrology and Hydraulic Engineering, Vrije Universiteit Brussel
address:
  street: Pleinlaan 2 
  city: 1050, Brussels, Belgium
  region: 
  postcode:
  country: 
  country_code: 
coordinates:
  latitude: 50.8225
  longitude: 4.3984
#office_hours:
#appointment_url: 
contact_links:
  - icon: twitter
    icon_pack: fab
    name: Twitter
    link: 'https://twitter.com/ivanderkelen'
  - icon: linkedin
    icon_pack: fab
    name: LinkedIn
    link: https://www.linkedin.com/in/inne-vanderkelen/
 # - #icon: google-scholar
    #icon_pack: ai
    #name: Google Scholar
    #link: https://scholar.google.be/citations?user=CDK0OBAAAAAJ&hl=nl
  #- #icon: github
    #icon_pack: fab
    #name: Github
    #link: https://github.com/Ivanderkelen
  #- #icon: researchgate
    #icon_pack: ai
    #name: Researchgate
    #link: https://www.researchgate.net/profile/Inne-Vanderkelen




# Site header

header:
  navbar:
    enable: true
    align: l
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: true

# Site footer

footer:
  copyright:
    notice: '© {year} Me. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-us

# Site features

features:
  syntax_highlighter:
    enable: true
    extra_languages:
      - r
      - latex
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/<username>/<repository>'
    content_dir: content
    branch: master
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: ''
    api_key: ''
    zoom: 15

# Extensions

extensions:
  cms:
    branch: main
    local_backend: false
  academicons:
    enable: true

# Security

security:
  # Allow frame for embedding speaker notes in slides
  allow_frame: true
